chore(deps): bump to ovh-ui-kit-bs v1.2.0 (#438)
## bump to `ovh-ui-kit-bs` v1.2.0

### Description of the Change

937f442 — chore(deps): bump to ovh-ui-kit-bs v1.2.0

Related to:

```sh
Running "less:development" (less) task
>> FileError: './ovh-ui-kit/packages/oui-action-menu/_mixins.less' wasn't found. Tried - node_modules/ovh-ui-kit-bs/src/oui/ovh-ui-kit/packages/oui-action-menu/_mixins.less,client/app/css/less/ovh-ui-kit/packages/oui-action-menu/_mixins.less,node_modules/ovh-ui-kit/packages/oui-action-menu/_mixins.less,node_modules/@bower_components/ovh-ui-kit/packages/oui-action-menu/_mixins.less,ovh-ui-kit/packages/oui-action-menu/_mixins.less in node_modules/ovh-ui-kit-bs/src/oui/_mixins.less on line 2, column 1:
>> 1 @import "@{oui-path}/packages/oui-accessibility/_mixins";
>> 2 @import "@{oui-path}/packages/oui-action-menu/_mixins";
>> 3 @import "@{oui-path}/packages/oui-animation/_mixins";
Warning: Error compiling client/app/css/source.less Use --force to continue.
```

/cc @jleveugle @Jisay @frenautvh